export enum CaseType {
  CIVIL_GENERAL = 'CIVIL_GENERAL',
  NON_ADVERSARIAL_GENERAL = 'NON_ADVERSARIAL_GENERAL',
  BANKING_CONSUMER = 'BANKING_CONSUMER',
  ALIMONY = 'ALIMONY',
  DIVORCE = 'DIVORCE',
  SEPARATION = 'SEPARATION',
  PROTECTION_PERSONAL_RIGHTS = 'PROTECTION_PERSONAL_RIGHTS',
  MATRIMONIAL_PROPERTY_DISSOLUTION = 'MATRIMONIAL_PROPERTY_DISSOLUTION',
  ESTATE_DIVISION_JOINT = 'ESTATE_DIVISION_JOINT',
  ESTATE_DIVISION_JOINT_AGREED = 'ESTATE_DIVISION_JOINT_AGREED',
  REAL_ESTATE_ZASIEDZENIE = 'REAL_ESTATE_ZASIEDZENIE',
  EASEMENT_ROAD_NECESSITY = 'EASEMENT_ROAD_NECESSITY',
  EASEMENT_TRANSMISSION = 'EASEMENT_TRANSMISSION',
  CO_OWNERSHIP_DISSOLUTION = 'CO_OWNERSHIP_DISSOLUTION',
  CO_OWNERSHIP_DISSOLUTION_AGREED = 'CO_OWNERSHIP_DISSOLUTION_AGREED',
  EVICTION_RESIDENTIAL = 'EVICTION_RESIDENTIAL',
  POSSESSION_DISTURBANCE = 'POSSESSION_DISTURBANCE',
  INHERITANCE_STATEMENT = 'INHERITANCE_STATEMENT',
  INHERITANCE_DIVISION = 'INHERITANCE_DIVISION',
  INHERITANCE_DIVISION_AGREED = 'INHERITANCE_DIVISION_AGREED',
  KRS_REGISTRATION = 'KRS_REGISTRATION',
  KRS_CHANGE = 'KRS_CHANGE',
  CONCILIATION_PROPOSAL = 'CONCILIATION_PROPOSAL',
  BAILIFF_COMPLAINT = 'BAILIFF_COMPLAINT'
}

export enum ProcedureType {
  STANDARD = 'STANDARD',
  WRIT_PROCEEDINGS = 'WRIT_PROCEEDINGS',
  ORDER_PAYMENT_ELECTRONIC = 'ORDER_PAYMENT_ELECTRONIC',
  APPEAL = 'APPEAL'
}

export interface CalculationResult {
  fee: number;
  description: string;
  legalBasis: string;
}
