
export enum CaseType {
  // General & Property
  CIVIL_GENERAL = 'CIVIL_GENERAL',
  BANKING_CONSUMER = 'BANKING_CONSUMER', // Art. 13a
  PAULIAN_ACTION = 'PAULIAN_ACTION', // Art. 13f
  
  // Family Law (Dział 3, Rozdział 1)
  DIVORCE = 'DIVORCE', // Art. 26
  SEPARATION = 'SEPARATION', // Art. 26
  PROTECTION_PERSONAL_RIGHTS = 'PROTECTION_PERSONAL_RIGHTS', // Art. 26
  MARRIAGE_PERMISSION = 'MARRIAGE_PERMISSION', // Art. 37
  MATRIMONIAL_PROPERTY_DISSOLUTION = 'MATRIMONIAL_PROPERTY_DISSOLUTION', // Art. 37
  ESTATE_DIVISION_JOINT = 'ESTATE_DIVISION_JOINT', // Art. 38
  ALIMONY = 'ALIMONY', // Free (Art. 96)
  
  // Property & Real Estate (Dział 4, Rozdział 2 & 3)
  EVICTION_RESIDENTIAL = 'EVICTION_RESIDENTIAL', // Art. 27
  POSSESSION_DISTURBANCE = 'POSSESSION_DISTURBANCE', // Art. 27
  REAL_ESTATE_ZASIEDZENIE = 'REAL_ESTATE_ZASIEDZENIE', // Art. 40
  CO_OWNERSHIP_DISSOLUTION = 'CO_OWNERSHIP_DISSOLUTION', // Art. 41
  LAND_REGISTER_OWNERSHIP = 'LAND_REGISTER_OWNERSHIP', // Art. 42
  LAND_REGISTER_MORTGAGE = 'LAND_REGISTER_MORTGAGE', // Art. 43
  LAND_REGISTER_DISCLOSURE = 'LAND_REGISTER_DISCLOSURE', // Art. 44/45
  
  // Inheritance (Rozdział 4)
  INHERITANCE_STATEMENT = 'INHERITANCE_STATEMENT', // Art. 49
  INHERITANCE_DIVISION = 'INHERITANCE_DIVISION', // Art. 51
  INHERITANCE_DIVISION_AGREED = 'INHERITANCE_DIVISION_AGREED', // Art. 51.2
  
  // Labor & Social Security (Rozdział 3)
  LABOR_EMPLOYEE = 'LABOR_EMPLOYEE', // Art. 35
  SOCIAL_SECURITY = 'SOCIAL_SECURITY', // Art. 36
  
  // Corporate & Business (Rozdział 2)
  COMPANY_DISSOLUTION = 'COMPANY_DISSOLUTION', // Art. 29
  ENVIRONMENTAL_PROTECTION = 'ENVIRONMENTAL_PROTECTION', // Art. 30
  PRIVATIZATION_TENDER = 'PRIVATIZATION_TENDER', // Art. 31
  KRS_REGISTRATION = 'KRS_REGISTRATION', // Art. 52
  KRS_CHANGE = 'KRS_CHANGE', // Art. 55
  
  // IP & Others
  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY', // Art. 26a
  CONSUMER_PROBATION = 'CONSUMER_PROBATION' // Art. 23a
}

export enum ProcedureType {
  STANDARD = 'STANDARD',
  WRIT_PROCEEDINGS = 'WRIT_PROCEEDINGS', // Nakazowe (Art. 19.2)
  ORDER_PAYMENT_ELECTRONIC = 'ORDER_PAYMENT_ELECTRONIC', // EPU (Art. 19.2 pkt 2)
  APPEAL = 'APPEAL', // Apelacja (Art. 18.2 - takes same fee as petition)
  PRIVATE_MEDIATION_SETTLEMENT = 'PRIVATE_MEDIATION_SETTLEMENT' // Art. 13e
}

export interface CalculationResult {
  fee: number;
  description: string;
  legalBasis: string;
  wps: number;
}
